=== kargarisaac/preauth-healthcare-ai-triage/schemas/PriorAuthorization.xsd
<xs:schema xmlns:tns="http://www.eclaimlink.ae/DHD/ValidationSchema" elementFormDefault="qualified" version="2.0" id="PriorAuthorization" xmlns:xs="http://www.w3.org/2001/XMLSchema">
 <xs:import schemaLocation="CommonTypes_20191113.xsd" namespace="http://www.eclaimlink.ae/DHD/ValidationSchema" />
    <xs:element name="Prior.Authorization">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="1" name="Header">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element minOccurs="1" maxOccurs="1" name="SenderID" type="tns:HeaderSenderID" />
                            <xs:element minOccurs="1" maxOccurs="1" name="ReceiverID" type="tns:HeaderReceiverID" />
                            <xs:element minOccurs="1" maxOccurs="1" name="TransactionDate" type="tns:HeaderTransactionDate" />
                            <xs:element minOccurs="1" maxOccurs="1" name="RecordCount" type="tns:HeaderRecordCount" />
                            <xs:element minOccurs="1" maxOccurs="1" name="DispositionFlag" type="tns:HeaderDispositionFlag" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element minOccurs="1" maxOccurs="1" name="Authorization">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element minOccurs="0" maxOccurs="1" name="Result" type="tns:AuthorizationResult" />
                            <xs:element minOccurs="1" maxOccurs="1" name="ID" type="tns:AuthorizationID" />
                            <xs:element minOccurs="0" maxOccurs="1" name="IDPayer" type="tns:AuthorizationIDPayer" />
                            <xs:element minOccurs="0" maxOccurs="1" name="DenialCode" type="tns:AuthorizationDenialCode" />
                            <xs:element minOccurs="1" maxOccurs="1" name="Start" type="tns:AuthorizationStart" />
                            <xs:element minOccurs="1" maxOccurs="1" name="End" type="tns:AuthorizationEnd" />
                            <xs:element minOccurs="0" maxOccurs="1" name="Limit" type="tns:AuthorizationLimit" />
                            <xs:element minOccurs="0" maxOccurs="1" name="Comments" type="tns:AuthorizationComments" />
                            <xs:element minOccurs="0" maxOccurs="unbounded" name="Activity">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element minOccurs="1" maxOccurs="1" name="ID" type="tns:ActivityID"  />
                                        <xs:element minOccurs="1" maxOccurs="1" name="Type" type="tns:ActivityType" />
                                        <xs:element minOccurs="1" maxOccurs="1" name="Code" type="tns:ActivityCode" />
                                        <xs:element minOccurs="0" maxOccurs="1" name="Quantity" type="tns:ActivityQuantity" />
                                        <xs:element minOccurs="1" maxOccurs="1" name="Net" type="tns:ActivityNet" />
                                        <xs:element minOccurs="0" maxOccurs="1" name="List" type="tns:ActivityList" />
                                        <xs:element minOccurs="0" maxOccurs="1" name="PatientShare" type="tns:ActivityPatientShare" />
                                        <xs:element minOccurs="1" maxOccurs="1" name="PaymentAmount" type="tns:ActivityPaymentAmount" />
                                        <xs:element minOccurs="0" maxOccurs="1" name="DenialCode" type="tns:ActivityDenialCode" />
                                        <xs:element minOccurs="0" maxOccurs="unbounded" name="Observation">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element minOccurs="1" maxOccurs="1" name="Type" type="tns:ObservationType" />
                                                    <xs:element minOccurs="1" maxOccurs="1" name="Code" type="tns:ObservationCode" />
                                                    <xs:element minOccurs="0" maxOccurs="1" name="Value" type="tns:ObservationValue" />
                                                    <xs:element minOccurs="0" maxOccurs="1" name="ValueType" type="tns:ObservationValueType" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== kargarisaac/preauth-healthcare-ai-triage/samples/prior_auth_request.xml
<?xml version="1.0" encoding="UTF-8"?>
<Prior.Authorization
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../schemas/PriorAuthorization.xsd">

  <!-- Header section -->
  <Header>
    <SenderID>PROV12345</SenderID>
    <ReceiverID>PAYER67890</ReceiverID>
    <!-- dd/mm/yyyy HH:MM format as required by HeaderTransactionDate type -->
    <TransactionDate>27/07/2025 10:32</TransactionDate>
    <RecordCount>1</RecordCount>
    <DispositionFlag>TEST</DispositionFlag>
  </Header>

  <!-- Authorization section -->
  <Authorization>
    <Result>Yes</Result>
    <!-- Unique authorization identifier -->
    <ID>PA-2025-000123</ID>
    <!-- Start & End in dd/mm/yyyy HH:MM format -->
    <Start>25/07/2025 00:00</Start>
    <End>25/07/2025 00:00</End>
    <!-- Human-readable comments / justification -->
    <Comments>Patient with poorly controlled diabetes; last HbA1c 9 months ago. No retinopathy screen in 18 months.</Comments>

    <!-- First activity -->
    <Activity>
      <ID>1</ID>
      <!-- 3 = CPT as per ActivityType enumeration -->
      <Type>3</Type>
      <Code>83036</Code>
      <Quantity>1</Quantity>
      <Net>120.00</Net>
      <PaymentAmount>0.00</PaymentAmount>
    </Activity>

    <!-- Second activity -->
    <Activity>
      <ID>2</ID>
      <Type>3</Type>
      <Code>92014</Code>
      <Quantity>1</Quantity>
      <Net>250.00</Net>
      <PaymentAmount>0.00</PaymentAmount>
    </Activity>
  </Authorization>

</Prior.Authorization>
